namespace H3Mapper.Flags
{
    public enum CreatureGeneratorType
    {
        ElementalConflux = 0,
        BehemothCrag = 1,
        PillarOfEyes = 2,
        HallOfDarkness = 3,
        DragonVault = 4,
        TrainingGrounds = 5,
        CentaurStables = 6,
        AirElementalConflux = 7,
        PortalOfGlory = 8,
        CyclopsCave = 9,
        ForsakenPalace = 10,
        SerpentFlyHive = 11,
        DwarfCottage = 12,
        EarthElementalConflux = 13,
        FireLake = 14,
        Homestead = 15,
        FireElementalConflux = 16,
        Parapet = 17,
        AltarOfWishes = 18,
        WolfPen = 19,
        GnollHut = 20,
        GoblinBarracks = 21,
        HallOfSins = 22,
        GorgonLair = 23,
        DragonCliffs = 24,
        GriffinTower = 25,
        HarpyLoft = 26,
        Kennels = 27,
        HydraPond = 28,
        ImpCrucible = 29,
        LizardDen = 30,
        MageTower = 31,
        ManticoreLair = 32,
        ChapelOfStilledVoices = 33,
        Labyrinth = 34,
        Monastery = 35,
        GoldenPavilion = 36,
        DemonGate = 37,
        OgreFort = 38,
        OrcTower = 39,
        HellHole = 40,
        DragonCave = 41,
        CliffNest = 42,
        Workshop = 43,
        CloudTemple = 44,
        DendroidArches = 45,
        Warren = 46,
        WaterElementalConflux = 47,
        TombOfSouls = 48,
        WyvernNest = 49,
        EnchantedSpring = 50,
        UnicornGlade = 51,
        Mausoleum = 52,
        Estate = 53,
        CursedTemple = 54,
        Graveyard = 55,
        Guardhouse = 56,
        ArchersTower = 57,
        Barracks = 58,
        MagicLantern = 59,
        AltarOfThought = 60,
        Pyre = 61,
        FrozenCliffs = 62, // Azure Dragons
        CrystalCavern = 63, // Crystal Dragons
        MagicForest = 64, // Faerie Dragons
        SulfurousLair = 65, // Rust Dragon
        EnchantersHollow = 66, // Enchanters
        TreetopTower = 67, // Sharpshooters
        UnicornGlade2 = 68, // A different shape of unicorn glade
        ALtarOfAir = 69,
        AltarOfEarth = 70,
        AltarOfFire = 71,
        AltarOfWater = 72,
        ThatchedHut = 73, // Halflings
        Hovel = 74,
        BoarGlen = 75,
        TombOfCurses = 76,
        NomadTent = 77, // Nomads
        RogueCavern = 78, // Rogues
        TrollBridge = 79,
        // Below are all WoG
        PortalOfSplendor = 80,
        DragonPeaks = 81,
        StormTemple = 82,
        UnholyPalace = 83,
        SpectralVault = 84,
        CaveOfDarkness = 85,
        BehemothTomb = 86,
        ChaosPool = 87,
        SpiritPyre = 88,
        VastCavern = 91, // Gorynych
        DreamHorseShoe = 92, // Nightmare
        LostFriary = 94, // War Zealot
        Snowman = 95, // Santa Gremlin
        SylvanHomestead = 96, // Sylvan Centaur
        EnchantedTower = 97, // Sorceress
        HowlingHollow = 98, // Werewolf
        HellfireRift = 99, // Hell Steed
        DragonGraveyard = 100, // Dracolich
        
       
    }
}